// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaXVfjONL+Kzp65wLecT6g6Y/JXsxJhzSd0xCyENjd07Acxa4kGmTJLclApsl/36MP",
	"O05sp2G2m9MXexfLVqlUqqrnqVK+4lDEieDAtcKdrzghksSgQdqnS8HSGAbRiOi5eY5AhZImmgqOO/iw",
	"d4IoV5rwENDgEO1EYdzIBho0QoxMgO3iAFPzeWKEBJiTGHAH31nRNzTCAZbwJaUSItzRMoUAq3AOMTEL",
	"ToWMicYdnKb2S71IzGSlJeUzvFwus4+tun0phSzrefahh96+a79FZquMEq4RmC+RBJUIrgAHOJEiAakp",
	"KDdfE8rKkj6mMeENCSQiEwYIHhJGODEvkUogpFMaIi2QnlOFRBimUgIPoay3sYgzU3mNC06/pIBoBFzT",
	"KQWJpkI6kU7rNcErA0nakDCF2hWVJjpVFXsaj0fIvUShiNaEUq5f7a+EUa5hBtJI01SzCuXP50JqNF83",
	"k0rjmMhFlVJuYFOKPUdk3mUaAU9j3PmMB8PL7vHg8KZ7dnRx0h+OcYCHp+ObD6cXw0Mc4O7xWb97+K+b",
	"/j8H5+NzHOBR/+xkcH4+OB3eHPaHg7756GLYvRh/7A/Hg153bEcGw3H/bNg9di8vu4Pj7vvjPg7wh+7g",
	"uH94Mzrr906Hh4Px4HSIr59u9GXRtT+7t5nprvOvxeQPCLWxxkcgrCrQ3Hh2SIryGQMtuPFfkcqw7L9J",
	"Zbz2CBechoQh8x6JKdJzKAqBBxIn5ljx3Gli9CfRKWeLLDSf7lZFnStkP8MdzryGziNWgbEm9fadaigt",
	"JJlBQ4G8oyE0EinuaASyGYVxk4pWvqvaA/zmdtNE07jK8SEUPLKHYxSdA/JKoEwJYwqpISpq/epNu127",
	"aCHa7kAqu0552Y1FJillEcq+Lxpor9lutr+9xWqfzY/RJ/HVAt4gJXcO8EODQNLI3cu5pQbJlRHsz+I6",
	"wAlLJWG5Y5hVchfPEYHyWcqILLqmX+8ZB2829ymdgOSgQY38Rx+pxz4SRdTYlbBRIZqmhCkINuy+ktLI",
	"E//osocUaE35TJUikoQhKHUTm3TW+Yp/kTDFHfx/rRX6tjyQtRzodu2EE/O9jTK7wZuQEVURbOfudc+8",
	"RQZg0Y64AylpBAqdj1AEU5IyvVsVcx6In66Z02lZkb+eaFF3pOs7yKauzDk3QtBUitiGU0g0YWJWMuxt",
	"fhLf0r7u5Cu34i16nkBYa+4c8x0DMDAdSiDGARCx7rBDTfDFRg27iURI7SAxk+Dj16y/W9pbSBISUr2o",
	"SolfUlAaolxS9i3ageasGaArvNduH9ErvLueBcygi2MTiriD//253fjt+tedq6um+7X7+06fPo7o45g+",
	"HtHHE/r4iT72H0eP48ejx5PHT7u//1LlRzFoEhFNnuhE2ddLu2l7HDfzzG+2zd84vAB7G95Ug8d5wcJF",
	"UrUTp0qjCaCrLLi8qTzT8IOFxFaTIdeWL5ghWB3f9RYHq4HPnqV4OsN8j9XZYeese6fHRBr176yHJWTB",
	"BIlQqkB5wsjTuLip0dnp5cCwocHwCAf47GLofzmigwN82D/uj92Y/dk/rLBA4AuDstpuPOcUSEIiQRmj",
	"5zGRM9+St5vYgZtqfB3TGJQmcYLu58CtMVziQvdEubCz0Joje0Q0NKysJ6A6jf6b6mazSPnmctX0LKc5",
	"lp3V0By3adXa238FB6/fvG3Au98mjb396FWDHLx+0zjYf/Nm72Dv7UG73X4SffMJblvEFXPhGuMjjJ1O",
	"cefz06a7acvrTa0sq4r+6tEzojRy8//q+W8GtNnns/lMdjBf88J2uUZu/Hu8xmXc4PO4jJ+zzKOwwBRK",
	"tjMB56gHMgDfRD3BtRRMIaI1CeexzTGhSAARHqEEZEyVYXbmA49mgl9xY0i0U8F6/oYUrMOYIRuUW9hX",
	"u80rXkg/Z0Cif0iq4dTF/5k/lxPCF/7RvrbP10W335xZk5COqdIVRiAzyo1/IEaVNrnU+08WzWW6xuFB",
	"3ySGcWlxCxXEe2yGLeRL0JLCnUlwxjXNTGRmmnUkqJRpVU+77GJUQ6yeBpurIgkTKcmimrxsQGx9psnA",
	"ym4kyziOzpRMYtPdFlb3tbzHTUhTWsToFhaNO8JSk+eoVK67QWYzixA8QlPKNFgJFTtzzaMqL7esl7r0",
	"EAo+pbNUQmSHVUKs08Tk4Rj4zOTeN68CHFOePe6tEyLS+NMwoZ3PDf/r/7OhGu6zWqWk2ypmVrqYRCZd",
	"lWhUX0ewJ1Tcz6wFJiLlketL2QWfsojPYtX2fm8FjkwNqDRw7VHfLmZzNLkjlBmi++zkaxe8rvfp2izn",
	"Qzpe7xd9oAzUQmmIcYDfMxHebqEzFxZFakmNA5mcZe3kjBseEsJN0kSCs4Vxwru955D5IdxX0PiMn86s",
	"Z0ik54Qj1/nT65x+/wdx+o2j2UJnl7ajORV2n4JrEto07Fu9hkmNpPAwmkpb62udqE6rNaN6nk6aoYhb",
	"hl8l7rPWNiAsZ5az/vkYdUcDm0tiwolNJknun7l1fdJFO5u+22OExmr3iguOChEbslRpkAoJjiYwJ2xq",
	"svph76R5xceGYLtFGRP3CnX7to/KIyIjl9ZCwd0q4QKRUAqlzNwMLZUDR0ZD4AoK9uomJJwD2rftmnVz",
	"3d/fN4l93RRy1vJzVet40OsPz/uN/Wa7OdcxK7RoixkoK1yzoiirpcw+Cl2drFm0DLBIgJOE4g5+1Ww3",
	"D3wHyDp0iyS0dbdHWDIne60Cns2gAoQNNCPC2MZZrDAY3VM9N8hJs456mph6GVslpB0bRF7SZc6mihcW",
	"nzcXPSEPNE5jxNN4AtIjsoU+ZdzD4nR2PfElBduj9ocQkwdHABT903bA8jsJ30zBndftilZ57JbEnb12",
	"u21Bxj+W+3rLoJ5VbKESVdoWqEpR1c2Attzb3XnYk9pvt7OQBW4PjSQJ8wyg9YdyLceVvG8TFMvAbD6o",
	"yqEqY0sQIZVaXjpNGVsYTzvYqksixYRB/OvzdHIXQhXqDPgdYTRC0vVRUMGLlgF+/bKqmKRNmE0LIN0l",
	"j02+2b2JD56Vz2syszVHNnJtakpRRX17FjwQQbyAMRuRV5MNd0uB54RdZjXL1sgrVc8XF4PD3SY6Am5E",
	"QoToFImYag1Rs8apbTH99LvAawdXoPR7ES2+m1+vVb/rmOir142Q2vvOIVUfThlr/NliyRIkp8dvL6eH",
	"pdIGQxTJyChhhn0ahkaVaxYe7O+/nEarLu0aKY+EKQaEdmr9lAnH54081ssZZxlUE4DsrqWOB5yBTiV3",
	"7fD52r1m1uN03KSUfY5Af1zdSv4gEPuYXRSVrJZRJqpQdoG5bjJ/4dmbQ3hbsJiXuMVgxY6RNReDqirk",
	"0I4jsvqnQTmPX/bKWdvNq8vaVcZYfdJa+wNIBX04qK2W3DaqUtPBy7l6VpgKjaamZv0pY80f7JZYC2pD",
	"yXKpbT4xWaANKK4KrB/kHe2XQ8JtvPJ/DrfucEegt3tbQnRYcUHh+iPG29aIZBPd7WXFmkI1XZFmye2c",
	"tO/ned+f+a11hZ5E/V7Q4X03ynbafx4OuGpfqbmk/JbymQ0G7x4Q7f4UIfmivLSLsn7731OhCWI0pvY+",
	"1Pusaq6udWvb1+hepCxCE0DwEAJEEL04m63msIQxcZ/BTh7zP2Xe8/lrG6n1fyeormk/vavvoOWdupZN",
	"R150zZ/iQsMRUZ4O1arkzfhnUMOqGJ1CuAgZuDan/WtJpaBsT8vr5X8CAAD//+LFoYLjKwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
