// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbNvL/Khj8+8L+l3qwk+Za3YuOIimOJraskRXf3UQ+D0SuRDQgwACgbTXWd7/B",
	"AylKpBS703h6M/dOBIHFYrH7298u9RWHIkkFB64V7nzFKZEkAQ3SPl0LliUwjMZEx+Y5AhVKmmoqOO7g",
	"fu8CUa404SGgYR8dRWHSyAcaNEKMzIEd4wDDA0lSBriDSZo2IqJJ486KxgGmRlRqNggwJ4mZ5N7d0ggH",
	"WMKXjEqIcEfLDAKswhgS4lTVGqRZ/e9PpPF7u/HLzZH/0bj52g7enKzz8eNff8AB1qvUSFdaUr7E6/U6",
	"l2bPOpBSyOohJ+966JfXP/0NGTsxSrhGYGYiCSoVXJkjpFKkIDUF5dZrQllV0vssIbwhgURkzgDBQ8oI",
	"J+YlUimEdEFDpAXSMVVIhGEmJfAQqnobkzkbV/f4yOmXDBCNgGu6oCDRQkgn0mm9JXghZEI07uBM0oaE",
	"BezdUWmiM1Vzpul0jNxLFIpoSyjl+tXpRhjlGpYgjTRNNatR/ioWUqN420wqSxIiV3VKuYFdKfYekXmX",
	"awQ8S3DnEx6Orrvnw/5td3L28WIwmuIAjy6nt+8uP476OMDd88mg2//X7eCfw6vpFQ7weDC5GF5dDS9H",
	"t/3BaDgwkz6Ouh+n7wej6bDXndqR4Wg6mIy65+7ldXd43n17PsABftcdng/6t+PJoHc56g+nw8sRvnm6",
	"0ddl3//k3uamuylmi/lvEGpjjfdAWF2UuvH8khTlSwZacOO/IpNh1X/T2mDvES44DQlD5j0SC6RjKAvZ",
	"xHjsNDH6k+iSs1Ueu093q7LONbKf4Q4Tr6HziE1gbEn9/LNqKC0kWUJDgbyjITRSKe5oBLIZhUmTilZx",
	"qr0X+M3jZqmmSZ3jQyh4ZC/HKBoD8kqgXAljCqkhKmv96k27vXfTUrTdgVR2n+q2O5vMM8oilM8vG+ik",
	"2W62v33Eep8trtGj/GYDb5CKOwf4oUEgbRTutYF7ZQT7u7gJcMoySVjhGGaXwsWLlEH5MmNEll3T7/eM",
	"izeH+5DNQXLQoMZ+0nvqEyeJImrsSti4FE0LwhQEO3bfSGkUwD++7iEFWlO+VJWIJGEISt0mBs46X/EP",
	"Eha4g/+vtUndLZ/IWi5jd+2CCzPfRpk94G3IiKoJtiv3umfeIpOB0ZG4AylpBApdjVEEC5IxfVwXcz5T",
	"P10zp9O6Br+eaFF3pdsnyJduzBkbIWghRWLDKSSaMLGsGPZzcRPf0n7fzdcexVv0KoVwr7mLnO8YgEnT",
	"oQRiHAAR6w5H1ARfYtSwh0iF1C4l5hJ8/Jr9jytnC0lKQqpXdZD4JQOlISok5XPRETSXzQDN8Em7fUZn",
	"eJu82UEXxwXzMvTqx6PZrOl+Hf96NKCPY/o4pY9n9PGCPn6gj4PH8eP08ezx4vFDLRMLcAKaGFr4RCfK",
	"Z6/toe113Ma53xxav3N5AfY2vK1PHlclC5dJ1VGSKY3mgGZ5cHlTeabhB0vAtgcht7YvmSHYXN/NAQfb",
	"kz57luLpPOf7XJ1fdkHZj3pMZNHgznpYSlZMkAhlCpQnjDxLyocaTy6vh4YNDUdnOMCTjyP/yxEdHOD+",
	"4HwwdWP256BfY4HAVxVVtd14wSmQhFSCMkYvYqJgvhVvN7EDt/X5dUoTUJokKbqPgVtjOOBC90S5sLOp",
	"tcjsEdHQsLKekNVp9L1Ko4Q8nANfGjr25lWAE8rzx5Pg+eXPNw9ST/wKAmV53x4C5VRWreoZvs0BPUoe",
	"CtsyoG7RRsLY5QJ3Pj1tuVu2vtnVylKz6I/6DyNKI7f+jzrRLiqYcz6bFOV38LUon9dbDMm/x1uEqLin",
	"ZxAiv2ZdhHKJblRsZ6LW8RdkWEIT9QTXUjCFiNYkjBMLVKFIAREeoRRkQpWhh2aCT4mCz7gxJDqqoU5/",
	"Rwq2c6FhLJRb7qCOmzNewrAJkOgfkmq4dCAy8fdyQfjKP9rX9vmm7OG7K/eg2jlVusYIZEm58Q/EqNIG",
	"kL3/5JBQ5XwcHvRtamibFp+hhr1PzbDlDRK0pHBnUNK4plmJzEqzjwSVMa32cze7GdWQqKfl3k2lhYmU",
	"ZFXPgHby9H5QyTOePUgOLo4TVUxiMfMANfxaPeNuXlRaJOgzrBp3hGUG0qhUrkVClkubZniEFpRpsBJq",
	"TuZaVHVebqkzdfAQCr6gy0xCZIdVSsI/BugN/+v/D7aynFpul4pum5jZ6GKATLpS06i+nQafULY/s6CY",
	"i4xHrrllN3zKJh7F6u391gocm0JSaeDaUwe7mcVockcoM2z52eBrN7zZ79N7Uc6HdLLddHpHGaiV0pDg",
	"AL9lIvxcxwptU28hLJMRXJPQgohvhxoyMZbCJ4FM2nJX61R1Wq0l1XE2b4YiaRmKkbpprUMwXo2LyeBq",
	"irrjoY2EhHBiQyEtrFtQRw8Z6GjX8j1GaKKOZ1xwVPK3kGVKg1RIcDSHmLCFwaR+76I541PDMd2mjIl7",
	"hboD20rkEZGRC8pQcLdLuEIklEIpszbHeuWgndEQuIKSvbopCWNAp7ZjsW2u+/v7JrGvm0IuW36tap0P",
	"e4PR1aBx2mw3Y52wUpeyHD957ZbXBXk5Yc5Ramzk/ZJ1gEUKnKQUd/CrZrv52jdBbNC0SEpbdyeEpTE5",
	"aZXQeAk1KcQkFkQY27mLTQZB91THBvdp3lTOUlMyYquEtGPDyEu6LrhAueH/aXfTC/JAkyxBPEvmIH0+",
	"scCtjHvYLJO38L9kYNu0/hIS8uDSl6K/2yZQ0bf3/QTc+ald0y1O3Ja4c9Juty1E+sdqa2sd7M+JBxJh",
	"nbalRFtWdTdMLXN0bX97U6ftdh6ywO2lkTRlPn+1flOu67aR9+30avmDxYO62kjlud7U7pllVYuMsZXx",
	"tNcHdUmlmDNIfnyeTu6bSI06Q35HGI2QdK0EVPKidYB/ellVTNYkzMICSPedw6J6/unAB8/G5zVZWsac",
	"j9yY4kfUEbeeTYqIIA73+yJvDxoeVwLPCbvOGffByLtMHb9BIaPAdc52ITLVZO7gTpEmGi4QFzrv40bB",
	"jOc9ZJDonjKGlsCNJoZjo2G/OeMzPnE5z/WXjkw0dwfjxsnp6XFnxhvopPHmFQpjIkloEZwJvjTjV5pI",
	"7bCGICbuQYZEAWJgyAsSEkV0SbWZaYg+oRwJzlaVmSrwoKICy7niVRoDV2bdgEdO/kammzrjT/mUuBPZ",
	"9iPixsX+3JK6Fh9sRLwV0epPhgbn/NvfQ9cVQDr5LrvWNmo8Y/yrIZHtYzk9fnk5PSyNNl6rSE5ECTPM",
	"c4XggSrXbXx9evpyGm3avFuEPBKmEBDaqfWXhGuPugVSVvF6HdTTp/xjzT4WNQGdSe766fHWh9G8SeqY",
	"XQW7z0C/33zW/E4U4H3+palitZxwUoXyL6DbJvNfTHsxhJ9LFvMSDxis3C2y5mKgawqcvh1HZPNXhWoW",
	"vO5Vc55bty/n1RljM6W19feTGvL1em8P2R2jDppev5yr50Wp0Ghh6tUXR4CLjGmaMltyK5QQHcbl5mWp",
	"Qf2XhAHvcwdgINgb5ZYkH3LX+QrtNOnrYv47OW775ZL0oYLhf7HwXxMLZ6AP5kP/KbO+mPjw8/7WRdEi",
	"aVlH9aL3/CEnNOkFFVGiNjQ7T13BHkBmdAHhKmTg+ku27KgVlJ9pfbP+TwAAAP//gtWyuZwoAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
