// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaXXMit9L+Kyq9ucBvhg97NzkJ5yLFYtZLrY0pwM45tfahxEwDymqkWUljm9j891P6",
	"mGFgBmynslt7ce4YfbRare6nH7V4xKGIE8GBa4XbjzghksSgQdqva8HSGPrRkOil+Y5AhZImmgqO2/i0",
	"e4EoV5rwEFD/FNWiMK5nDXUaIUZmwI5wgOGBxAkD3MYkSeoR0aR+Z0XjAFMjKjELBJiT2AxyfVMa4QBL",
	"+JJSCRFua5lCgFW4hJg4VbUGaWb/5xOp/9mq/3pb8z/qt4+t4OfjddZ+9NsPOMB6lRjpSkvKF3i9XmfS",
	"7F57UgpZ3uTofRf9+vanfyBjJ0YJ1wjMSCRBJYIrs4VEigSkpqDcfE0oK0v6kMaE1yWQiMwYIHhIGOHE",
	"dCKVQEjnNERaIL2kCokwTKUEHkJZb2MyZ+PyGlecfkkB0Qi4pnMKEs2FdCKd1luC50LGROM2TiWtS5jD",
	"3hWVJjpVFXuaTIbIdaJQRFtCKddvTjbCKNewAGmkaapZhfLjpZAaLbfNpNI4JnJVpZRr2JVizxGZvkwj",
	"4GmM259wf3DdOe+fTjujs6uL3mCCAzy4nEzfX14NTnGAO+ejXuf039Pev/rjyRgHeNgbXfTH4/7lYHra",
	"G/R7ZtDVoHM1+dAbTPrdzsS29AeT3mjQOXed153+eefdeQ8H+H2nf947nQ5Hve7l4LQ/6V8O8O3Ljb4u",
	"+v4n15uZ7jYfLWZ/QKiNNT4AYVVR6tqzQ1KULxhowY3/ilSGZf9NKoO9S7jgNCQMmX4k5kgvoShkE+NL",
	"p4nRn0SXnK2y2H25WxV1rpD9CncYeQ2dR2wCY0vq519UXWkhyQLqCuQdDaGeSHFHI5CNKIwbVDTzXe09",
	"wGe3myaaxlWOD6HgkT0co+gSkFcCZUoYU0gNUVHrNz+3WnsXLUTbHUhl1ykvu7PILKUsQtn4ooGOG61G",
	"6/ktVvtsfowe5TcLeIOU3DnAD3UCST13rw3cKyPYn8VtgBOWSsJyxzCr5C6epwzKFykjsuiafr1XHLzZ",
	"3Md0BpKDBjX0gz5QnzhJFFFjV8KGhWiaE6Yg2LH7Rko9B/7hdRcp0JryhSpFJAlDUGoaGzhrP+IfJMxx",
	"G/9fc5O6mz6RNV3G7tgJF2a8jTK7wWnIiKoItrHr7ppeZDIwqok7kJJGoNB4iCKYk5Tpo6qY85n65Zo5",
	"ndYV+PVCi7oj3d5BNnVjzqURguZSxDacQqIJE4uSYT/nJ/Gc9vtOvnIr3qLjBMK95s5zvmMAJk2HEohx",
	"AESsO9SoCb7YqGE3kQipXUrMJPj4NesflfYWkoSEVK+qIPFLCkpDlEvKxqIaNBaNAN3g41brjN7gbfJm",
	"G10c58zL0Ksfazc3Dffr6Ldajz4N6dOEPp3Rpwv69JE+9Z6GT5Ons6eLp4+VTCzAMWhiaOELnSgbvbab",
	"tscxXWZ+c2j+zuEF2NtwWp08xgULF0lVLU6VRjNAN1lweVN5puEbC8C2ByG3li+YIdgc3+0BB9uTPruW",
	"4uks5/tcnR12TtlrXSbSqHdnPSwhKyZIhFIFyhNGnsbFTQ1Hl9d9w4b6gzMc4NHVwP9yRAcH+LR33pu4",
	"Nvuzd1phgcDfKspqu/acUyAJiQRljJ7HRM58S95uYgem1fl1QmNQmsQJul8Ct8ZwwIXuiXJhZ1Nrntkj",
	"oqFuZb0gq9Poa12NYvJwDnxh6NjPbwIcU559Hgevv/48u5Fq4pcTKMv79hAop7JqlvfwPAf0KHkobIuA",
	"ukUbCWOXc9z+9LLpbtr6dlcrS82iv+o/jCiN3Py/6kS7qGD2+WpSlJ3BY359Xm8xJN+PtwhRfk6vIER+",
	"zjoP5QLdKNnORK3jL8iwhAbqCq6lYAoRrUm4jC1QhSIBRHiEEpAxVYYemgE+JQp+w40hUa2COv0TKdjO",
	"hYaxUG65gzpq3PACho2ARL9LquHSgcjIn8sF4Sv/abvt923Rw3dn7kG1c6p0hRHIgnLjH4hRpQ0ge//J",
	"IKHM+Tg86GliaJsWn6GCvU9Ms+UNErSkcGdQ0rimmYnMTLOOBJUyrfZzN7sY1RCrl+XezU0LEynJqpoB",
	"7eTp/aCSZTy7kQxcHCcqmcRi5gFq+Fje425eVFrE6DOs6neEpQbSqFSuREIWC5tmeITmlGmwEip25kpU",
	"z+G9EbPxVZu6HLPu9Ib145OTo7+E7nX/6/8P1rWcjiohVQWiglL5KINq0t07jaLbOfEFd/hX3i5mIuWR",
	"q3TZBV+yiIe0auO/swKH5lapNHDteYRdzAI2uSOUGer8aiS2C97ud/C9kOfjO96uQL2nDNRKaYhxgN8x",
	"EX6uooi2wjcXltYIrkloEcXXRo2nDaXwGSGV9u6rdaLazeaC6mU6a4Qibhq+kbhhzUOYXg6SUW88QZ1h",
	"34ZFTDixcZHk1s15pMcPVNu1fJcRGqujGy54MQhClioNUiHB0QyWhM0NQJ12Lxo3fGIIp1uUMXGvUKdn",
	"64o8IjJyERoK7lYJV4iEUihl5mbArxzOMxoCV1CwVych4RLQiS1fbJvr/v6+QWx3Q8hF089VzfN+tzcY",
	"9+onjVZjqWNWKFkW4ye7yGWXhOxuYfZRqHJkxZN1gEUCnCQUt/GbRqvx1ldEbNA0SUKbd8eEJUty3CxA",
	"8wIq8onJMogwtnMWm3SC7qlemiRAswpzmpj7I7ZKSNvWj7yk65wYFKv/n3YXvSAPNE5jxNN4BtInF4vi",
	"yriHTTlZPf9LCrZm6w8hJg8ulyn6p60I5UV8X1zA7Z9aFaXj2C2J28etVstCpP8s17nWwf4EeSArVmlb",
	"yLpFVXfD1NJI9wZgT+qk1cpCFrg9NJIkzCez5h/KleA28p7PtZZMWDyouiipLPGbi3xqKdY8ZWxlPO3t",
	"QV0SKWYM4h9fp5N7IKlQp8/vCKMRkq6ugApetA7wT99WFZM1CbOwANI9elhUz94RfPBsfF6ThaXPWcut",
	"uQmJKhbXtUkREcThfl/k7UHDo1LgOWHXGf0+GHmXiSM7KGQUuM6oL0Roh3c00O8m33lwjwJENbq4Gk9u",
	"eEx0uLQ1p0ZGuRrG3f0MEVOtzQQTKkUiQxXSxMaRFPENLwvYUBrPtJ976tsJNvvItzn1v/fKWxmy1knf",
	"iWj1N0er88ft98p1CSOOv8qqlYUUT+K+N3CwdSanx6/fTg9vE5sXbTWMxNueXstI+hEizLDEFYIHqlyZ",
	"8O3JybdTdVOf3SLPkTCkXWin1ncJrR4hc1QrY+s6qKY62SvLPsYzAp1K7grhy60Xzay66VhYCWfPQH/Y",
	"vEd+pXT9IXsiKlktI4dUoezpcttk/qmzu4Twc8FiXuIBgxXLPNZcDHTVzdS2I7L5j0E5Y113y/nJzduX",
	"n6qMsRnS3PrfSAVReru3+Ou2UYVZb785VphYm5u75XcZa/5gD8RasDeULGs85BOz1S61qAqsr+QdrW+X",
	"Ig8x6P853LbDnYE+iOz+Na2awn78Zf+FOb+YN603eNF7/hMSGqBEuSuqDZPMQDjYAy2MziFchQxcVcO+",
	"rFYKyva0vl3/NwAA///MS9r2HycAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
